### ISSUE TITLE
Localization for qt

### ISSUE THREAD

**Issue by glixx** [xaos-project/XaoS#104]
To create ts files by lupdate needs to have tr in code.
Transifex can convert po files in ts files automatically. Needs to have blank.ts only.
But qt can be localized by po files too without ts files, but this way is not standard for qt localization. But if you're interested to keep po files I'll give you workable example.
In case to use ts files I need blank.ts to give you converted ts files.

**Comment by jblang** [comment]
Since all the other translations are po files, I would prefer to keep that format for now. Qt Linguist can import them, and hopefully export ts files.  Once I do some more research on code changes necessary to get Qt to do translation in non-C++ code, I will test whether I can make it work with the existing translations.  Once Qt becomes established as the default GUI we can re-evaluate whether to switch to ts files going forward.  I would like to have at least one release with Qt and make sure it works for the majority of users before I make too many invasive changes that tie us too closely to Qt.

**Comment by glixx** [comment]
Yes. You can keep both po and ts.
If to configure transifex to use translation memory in this case translator can translate any string from any file and it will be translated automatically in other file that has same string.
But needs to have blank.ts.
Transifex even will help to translate desktop file.
So I highly recommend to use transifex for xaos.
Using transifex you need only blank.ts, xaos.pot, you don't need export/import by qtlinguist.

**Comment by jblang** [comment]
I can only speak English so I am not going to do any translating on my own. I am happy to do what I can to help people who want to use Transifex to do translations if they want to, but I also don't want to make it a requirement. For people who want to use traditional text editor to maintain the po and cat files, or possibly use Qt Linguist in the future, I want to leave that option available.

**Comment by glixx** [comment]
But transifex is not only online tool.
Translator can download translation from transifex or from here, translate by qtlinguist and upload into transifex.
There are 2 ways to upload there:
Adding new translated strings only
Changing all strings (delete all translated strings and go by 1st way)

**Comment by jblang** [comment]
Qt translation is working now.
