### ISSUE TITLE
Custom Gradients/Palette Support

### ISSUE THREAD

**Issue by jblang** [xaos-project/XaoS#15]
_From [jb.langs...@gmail.com](https://code.google.com/u/110414581290182795947/) on May 04, 2009 18:37:45_

Current XaoS only supports automatically generated palettes using random
seeds and one of three algorithms.  We should provide the ability to load
custom palettes from Fractint .map or GIMP .gpl formats (basic format for
both is simple RGB triplets in a text file).

_Original issue: http://code.google.com/p/gnuxaos/issues/detail?id=16_

**Comment by jblang** [comment]
This [fork](https://github.com/u8sand/XaoS/tree/fractint-maps) has support for Fractint Maps. We should get it merged if it works.

**Comment by kovzol** [comment]
The fork https://github.com/u8sand/XaoS/tree/fractint-maps seems to be just an initial idea but it does not work out of the box.

My concern is that most users are not familiar with Fractint or GIMP palettes, so importing them will not be very useful.
However, GIMP has a powerful palette editor with import and export features.

On the other hand, when editing a palette in XaoS (this is not possible at the moment), the user may want to save it. Then it would be logical to use a well-known format (maybe .gpl).

For me the following seems to be the most useful way:
1) Show a ring (https://en.wikipedia.org/wiki/Annulus_(mathematics)) with the default colors (27), each color could be shown as an annular sector. XaoS uses a set of base colors (by default, 27) that are interpolated into a lot of gradient colors. Users can, however, cannot overview and edit so many colors at the same time. So, I think, we can maximize the number of base colors (maybe 27 is actually enough) and use them instead of the 27 default ones on the user's demand.
2) The annular colors can be edited by the user.
3) They can be eventually saved and loaded as a .gpl file.

This is not a completely general solution, but maybe enough for most users.
